# Generated by Django 6.0 on 2026-01-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='Product',
            new_name='product',
        ),
    ]
