# Generated by Django 6.0 on 2026-01-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_statud_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email_name',
            new_name='email',
        ),
    ]
